// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyzievegnndiultkqvhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5emlldmVnbm5kaXVsdGtxdmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjEyNDAsImV4cCI6MjA3MDgzNzI0MH0.4GTMrS1eo-Jjk2IqISn49bcBXZjS3KNNlqV1oswYgro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});